### ISSUE TITLE
gmpublisher.download link is banned from Steam

### ISSUE THREAD

**Issue by Hansmeru** [WilliamVenner/gmpublisher#107]
Whenever you try to upload an addon, it instantly gets banned from workshop, and it won't let you edit/make it public/nothing at all. It happens so cause the gmpublisher link was banned from Steam. 

If you have already have an addon on workshop and want to update it, remove the link from the description before doing so, otherwise it will get banned too.
If you want to upload an addon, use another tool to upload it, then gmpublisher for the next updates.

![image](https://user-images.githubusercontent.com/37870969/185722112-115d6207-de85-4b9d-850e-73ee9146d1ae.png)

**Comment by WilliamVenner** [comment]
Fixed in next update!
