### ISSUE TITLE
There was a problem trying to save the title and description. Access was denied.

### ISSUE THREAD

**Issue by erixlxme** [WilliamVenner/gmpublisher#110]
There was a problem trying to save the title and description. Access was denied.

I cant change the description for some reason? Does anyone know why?
Heres a pic
![image](https://user-images.githubusercontent.com/76689272/185795033-e0524b95-3f35-4330-9e7a-a7411f220c21.png)

**Comment by erixlxme** [comment]
the icon problem is fixed but the description thingy isnt

**Comment by WilliamVenner** [comment]
This doesn't have anything to do with gmpublisher
