### ISSUE TITLE
This item is awaiting analysis by our automated content check system. It will be temporarily hidden until we verify that it does not contain harmful content (e.g. links to websites that attempt to steal information).

### ISSUE THREAD

**Issue by erixlxme** [WilliamVenner/gmpublisher#111]
Its been stuck like this for 3 hours? How to fix?

**Comment by WilliamVenner** [comment]
Ask Valve, not me. I am not Valve, I did not make Steam, I did not make the Workshop.

**Comment by zxcold** [comment]
sorry to bring this up again but the auto "uploaded with gmpublisher" description is setting this off.
I had the same issue, contacted valve support and got it cleared, uploaded again and instantly happened, I had noticed after the fix they had removed the link but the reupload had put it back and their for triggered the flag again.
can we have an option to turn this off?

**Comment by WilliamVenner** [comment]
Update gmpublisher....

**Comment by zxcold** [comment]
its the update to 2.9.2 that started this problem for me, thinking of going back a version. or am i missing something?

**Comment by zxcold** [comment]
Maybe its because i cant edit the description when it gets uploaded that it keeps doing it even when the link is removed.
sorry for the trouble.
