### ISSUE TITLE
my downloaded addon is stuck on the content check system

### ISSUE THREAD

**Issue by Monstermercado** [WilliamVenner/gmpublisher#113]
i'm trying to delete the addon but its stuck on the automated 
![Screenshot_10](https://user-images.githubusercontent.com/111790931/185995301-cc4e657f-4bc7-4863-aeeb-7ccb3ecdf631.png)
 check system. help. #

**Comment by WilliamVenner** [comment]
Not the fault of gmpublisher. Please contact Steam

**Comment by Monstermercado** [comment]
do i need to make a ticket?
