### ISSUE TITLE
Using gmpublisher causes uploads to be blacklisted?

### ISSUE THREAD

**Issue by lucasesquivel** [WilliamVenner/gmpublisher#115]
Ever since the banning of the auto-link it appears that any upload that used gmpublisher is getting frozen, awaiting a "check from the automated system" for multiple days. The only thing me and other people can do to have access to our posts again is to ask steam support, but changing anything will revert it to its automated review. People have also reported not having this problem with GMPU, I have tried it and have had no issues. I don't know if steam is being triggered by gmpublisher, but it's sad I can't use this software anymore.

**Comment by Hansmeru** [comment]
Just update it, the fixed version is on the latest released

**Comment by lucasesquivel** [comment]
I am on the fixed version. To be very clear, 2.9.1 results in the above issue.



> Just update it, the fixed version is on the latest released

**Comment by ShinyaKogami** [comment]
Still the same issue, Steam Verify Bans it for hours.

**Comment by WilliamVenner** [comment]
Fixed in 2.9.2, I uploaded something myself and it worked fine.
