### ISSUE TITLE
map icon

### ISSUE THREAD

**Issue by Shajden** [WilliamVenner/gmpublisher#116]
when i want my map to have icon it says that i cant upload it because there is a png file in maps folder
the how the hell i can upload map with icon
before upload:
![image](https://user-images.githubusercontent.com/110666018/186881788-d2bafeee-02c5-4cf9-b6a5-8968e469c738.png)
after upload:
![image](https://user-images.githubusercontent.com/110666018/186881837-294a30e0-b158-4f7a-aab3-72156ad21b6e.png)

**Comment by WilliamVenner** [comment]
put it in maps/thumb/map_name.png

https://wiki.facepunch.com/gmod/Workshop_Addon_Creation#preparingyouraddon
