### ISSUE TITLE
uploaded addon is stuck on awaiting analysis for hours

### ISSUE THREAD

**Issue by niik128** [WilliamVenner/gmpublisher#123]
i tried uploaded a small addon 3 times using gmpublisher and they keep getting stuck for hours on awaiting analysis and i cant remove them. Then i used gmad and it uploaded fine

**Comment by WilliamVenner** [comment]
Update gmpublisher.

**Comment by niik128** [comment]
its the latest version 2.9.2

**Comment by WilliamVenner** [comment]
Doesn't happen for me, I just uploaded a test addon fine.
