### ISSUE TITLE
Macs Cant open .MSI files.

### ISSUE THREAD

**Issue by Purplous** [WilliamVenner/gmpublisher#125]
Either im Stupid or im blind or what ever but 
A: Mac Cant Open MSI Files Natively
B: I Cant Find a DMG Or APP File anywhere 
C: I Dont Know If I Am Blind But As Far as im awaare theres no mention of needing a external app to open MSI files.

**Comment by WilliamVenner** [comment]
There's no macos builds at the moment

**Comment by neumann-dev** [comment]
@Badger9 
Could you do a macOS-Build of the latest version?

**Comment by DylanSCRIPTGUY** [comment]
Yeah Please make a macos version!
