### ISSUE TITLE
I can't install msi

### ISSUE THREAD

**Issue by Lavandos1488** [WilliamVenner/gmpublisher#126]
![image](https://user-images.githubusercontent.com/113255642/189507898-dd0c91f2-9774-4436-a857-c6d9309db0ce.png)
I thought the problem was in my installer. I tried to fix the problem in many ways using cmd and regedit, but nothing helped. Other msi installers like a blackhole.msi are working.

**Comment by WilliamVenner** [comment]
Could you try installing the Webview 2 runtime manually? https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by Lavandos1488** [comment]
Installing Webview 2 runtime as administrator helped. Thank you.
