### ISSUE TITLE
Uninstalling

### ISSUE THREAD

**Issue by randock233** [WilliamVenner/gmpublisher#130]
I cant even uninstall it smh

**Comment by WilliamVenner** [comment]
Control Panel

**Comment by randock233** [comment]
i cant ... 
![image](https://user-images.githubusercontent.com/60582130/192108190-53cc5e39-d6c6-4db1-b98d-741aa744b686.png)

**Comment by WilliamVenner** [comment]
blame microsoft for webview2

**Comment by randock233** [comment]
what can i do ? 💀i need to download the latest version but i cant

**Comment by randock233** [comment]
> blame microsoft for webview2


what can i do ? 💀i need to download the latest version but i cant

**Comment by WilliamVenner** [comment]
https://kb.foxitsoftware.com/hc/en-us/articles/360040660391-Fix-Error-2502-and-2503-while-installing-or-uninstalling
