### ISSUE TITLE
Application won't launch

### ISSUE THREAD

**Issue by DaBigEgg** [WilliamVenner/gmpublisher#14]
Hello, I deleted the old application to download the new update, and now it won't open. I have WebView 2

**Comment by WilliamVenner** [comment]
Please do this:

https://i.venner.io/izKHvVkmJv.mp4

Here's the command:

`gmpublisher > output.msg 2> output.err`

Send the output.msg and output.err here

You can open cmd in a specified folder by entering this command

`cd C:\Users\your_username\Desktop\gmpublisher-files` (for example)

**Comment by DaBigEgg** [comment]
Ok, on it. This is my task manager rn O_o
![image](https://user-images.githubusercontent.com/79529277/115966582-361ad300-a526-11eb-911c-b58fab07035f.png)

**Comment by DaBigEgg** [comment]
How should I upload them, as GitHub doesn't support the file type.

**Comment by WilliamVenner** [comment]
you can probably just pop them in a zip

**Comment by WilliamVenner** [comment]
that's probably from spamming opening it, but it's weird that it hasn't crashed and appears to just be hanging and using a load of cpu...

**Comment by DaBigEgg** [comment]
[win64.zip](https://github.com/WilliamVenner/gmpublisher/files/6370193/win64.zip)

**Comment by DaBigEgg** [comment]
I restarted my PC and clicked once, twice at the most

**Comment by WilliamVenner** [comment]
theres nothing in it lol?

![image](https://user-images.githubusercontent.com/14863743/115966894-8cd4dc80-a527-11eb-8c47-bb62eadb5e63.png)

**Comment by WilliamVenner** [comment]
did github do that?

just put .txt on the end of them i guess :D

**Comment by DaBigEgg** [comment]
[win64.zip](https://github.com/WilliamVenner/gmpublisher/files/6370195/win64.zip)
tf. sorry bout that

**Comment by DaBigEgg** [comment]
It didn't zip properly on my end

**Comment by WilliamVenner** [comment]
the files are empty, are they actually empty or did the zip bork them again?

**Comment by DaBigEgg** [comment]
![image](https://user-images.githubusercontent.com/79529277/115966995-08cf2480-a528-11eb-8637-b33bb5960f03.png)

**Comment by WilliamVenner** [comment]
does it contain anything if you close gmpublisher?

**Comment by DaBigEgg** [comment]
I can't close it. Even when I end tasks in task manager, they still stick

**Comment by WilliamVenner** [comment]
end the processes in the details tab

**Comment by DaBigEgg** [comment]
![image](https://user-images.githubusercontent.com/79529277/115967172-f5708900-a528-11eb-8b10-1f3cc47109e1.png)

**Comment by WilliamVenner** [comment]
can you just restart the computer and try this all again lol

**Comment by DaBigEgg** [comment]
Yes. Try the command again or just uploading the files?

**Comment by WilliamVenner** [comment]
Try the command and upload the files

**Comment by DaBigEgg** [comment]
![image](https://user-images.githubusercontent.com/79529277/115967390-4e8cec80-a52a-11eb-8482-7aa6d203966d.png)
Didnt even open it

**Comment by DaBigEgg** [comment]
I dragged to my Desktop. Changed them to .txt and they are both blank

**Comment by WilliamVenner** [comment]
you closed gmpublisher right?

**Comment by DaBigEgg** [comment]
I restarted my PC and didn't open it

**Comment by WilliamVenner** [comment]
wat. how could it be open then

**Comment by DaBigEgg** [comment]
Exactly xD

**Comment by WilliamVenner** [comment]
running it in cmd opens it

it's probably in your task manager, just end the process

**Comment by DaBigEgg** [comment]
Both files have been renamed and are empty

**Comment by WilliamVenner** [comment]
try this build, it should open a console automatically

[win64.zip](https://github.com/WilliamVenner/gmpublisher/files/6370247/win64.zip)

**Comment by DaBigEgg** [comment]
gmpublisher v2.0.2
Setting breakpad minidump AppID = 4000
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561199128295593 [API loaded no]
[Steam] Client initialized

**Comment by WilliamVenner** [comment]
Give this one a try. It's more verbose.

[win64.zip](https://github.com/WilliamVenner/gmpublisher/files/6370303/win64.zip)

**Comment by DaBigEgg** [comment]
gmpublisher v2.0.2
Initializing Steamworks...
Setting breakpad minidump AppID = 4000
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561199128295593 [API loaded no]
[Steam] Client initialized

**Comment by DaBigEgg** [comment]
Basically, same thing again lol

**Comment by WilliamVenner** [comment]
Think I tracked down the issue... give this one a try.

[win64.zip](https://github.com/WilliamVenner/gmpublisher/files/6370421/win64.zip)

**Comment by DaBigEgg** [comment]
Exactly the same :/

**Comment by DaBigEgg** [comment]
For clarification, the last Alpha build is the last version I can open

**Comment by TomDotBat** [comment]
yo this broke bro

**Comment by DaBigEgg** [comment]
You don't say xD

**Comment by WilliamVenner** [comment]
what specs is your computer?

**Comment by DaBigEgg** [comment]
1660ti
Intel i5

**Comment by WilliamVenner** [comment]
Full specs please

**Comment by DaBigEgg** [comment]
What specs do you need?

**Comment by WilliamVenner** [comment]
Well... turned out it was an antivirus ._.
