### ISSUE TITLE
Steam Interference

### ISSUE THREAD

**Issue by SirPlancake** [WilliamVenner/gmpublisher#180]
Whenever I launch GMPublisher, it always thinks I'm playing Garry's Mod. I wonder if you can somehow make it so it doesn't interfere with steam. It also stays open in the background making it so steam can't close unless you manually close GMPublisher in the task manager as it does not show in tray.

**Comment by LillyWho** [comment]
GMP needs to use the Steam API and log into the API as Garry's Mod in order to operate. Whenever you don't actively need GMP and it's not performing an operation, simply close it.

**Comment by WilliamVenner** [comment]
Hi, LillyWho is correct – this is just how gmpublisher uses Steamworks. Unfortunately, fixing this would require a rewrite, and regardless, I don’t think opening and closing a Steamworks instance every time we need to make an API call is a good idea, so this quirk will remain. The program is not really intended to be left open, anyways

**Comment by SirPlancake** [comment]
Alright.
