### ISSUE TITLE
Update GMAD whitelist/blacklist for gmpublisher (color correction .raw)

### ISSUE THREAD

**Issue by Mingooberus** [WilliamVenner/gmpublisher#199]
As of commit garrysmod.main/main#befdaf color correction .raw files are now supported unpacked in addons for maps using the following path materials/colorcorrection/*.raw

Attempting to upload an addon using gmpublisher fails claiming that .raw files are not allowed, even if the *.raw filetype is removed from the ignored file-types. 

Would this be able to be fixed? Maybe add a settings file for the manual addition of possible future allowances, would help if this program goes unsupported.

**Comment by WilliamVenner** [comment]
Fixed in 2.10.0
