### ISSUE TITLE
gmpublisher canont see any files

### ISSUE THREAD

**Issue by Zamurovka** [WilliamVenner/gmpublisher#203]
After one publish, I cannot chose any .bsp files and I dont know why
![image](https://github.com/WilliamVenner/gmpublisher/assets/153458025/b8f83fdb-659b-48d9-abe0-60bd22e71885)
![image](https://github.com/WilliamVenner/gmpublisher/assets/153458025/9927945b-7047-49b2-a199-25bd9902e8f8)

**Comment by WilliamVenner** [comment]
Choose “addon” as the folder, not “maps”
