### ISSUE TITLE
[Linux] Settings, and create new add-on GUI doesn't displaying

### ISSUE THREAD

**Issue by Turelk** [WilliamVenner/gmpublisher#210]
When I try to open settings or new add-on menu, visually nothing happens, although in reality these menus open, but are not displayed.
Video: 

https://github.com/WilliamVenner/gmpublisher/assets/157890839/0250c9ff-a7cb-4637-bd2a-0af4a33c1024

**Comment by WilliamVenner** [comment]
Can't reproduce, sorry. Maybe a problem with hardware acceleration. What OS is that?

**Comment by St1X89** [comment]
I cant even run on Arch lol

**Comment by PenguinDOOM** [comment]
The same goes for my Arch.

**Comment by Turelk** [comment]
> Can't reproduce, sorry. Maybe a problem with hardware acceleration. What distro is that?

That is SteamOS 3.0 (Arch Linux)

**Comment by WilliamVenner** [comment]
To be honest, even if I installed Arch and reproduced the problem, I wouldn't know how to fix it. Additionally, as far as I can tell, the problem appears to only happen on Arch?

I believe the problem has something to do with hardware acceleration. When opening the settings panel, it uses a CSS `transform` transition to animate in which makes use of the GPU. Everything else appears to be working in the video, but CSS `transform` transitions don't work. That is a complete mystery to me, and I have no control over it as the OS provides the WebView.

Sorry I cannot be of more help.

**Comment by Hatchet-ManDev** [comment]
Hello there.
I have the same issue on Manjaro KDE and I'm getting the only error in the terminal when running the application: `src/nv_gbm.c:242: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)`

I am not sure if this is helpful or anything, but if the problem is GPU acceleration (as I understand from the last comment), so is it possible to add an option to turn it off by default or transitioning animations at least?

**Comment by RavMda** [comment]
Try adding `WEBKIT_DISABLE_COMPOSITING_MODE=1`, it fixed the issue for me

Should look something like this: 
```LD_LIBRARY_PATH=/path/to/gmpublisher WEBKIT_DISABLE_COMPOSITING_MODE=1 /path/to/gmpublisher/gmpublisher```

**Comment by WilliamVenner** [comment]
Awesome, thank you. If others can confirm this fixed the issue for them, I’ll set that environment variable when gmpublisher starts.

**Comment by Hatchet-ManDev** [comment]
I have tried the `export WEBKIT_DISABLE_COMPOSITING_MODE=1` and can confirm everything now works fine. 
![Screenshot_20240312_185612](https://github.com/WilliamVenner/gmpublisher/assets/108741822/c95973f0-1a07-49fd-96f9-47d95acae37b)

_Also I've seen another issue (may be related to Arch-based users with proprietary NVIDIA drivers) such as `Failed to create GBM buffer` and the line `export WEBKIT_DISABLE_DMABUF_RENDERER=1` seems to solve this one, at least I have no issues in terminal now and can work with addons freely._
