### ISSUE TITLE
[Linux] Cannot open GMPublisher

### ISSUE THREAD

**Issue by Hatchet-ManDev** [WilliamVenner/gmpublisher#213]
Downloaded it and unpacked in Downloads folder. I'm getting this error when trying to open the application via terminal:
`./gmpublisher: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory`

Its a strange thing as the library file is in the same folder as the application. I use Manjaro KDE.

**Comment by pepchek** [comment]
Use `LD_LIBRARY_PATH=/path/to/gmpublisher` variable

**Comment by Hatchet-ManDev** [comment]
> Use `LD_LIBRARY_PATH=/path/to/gmpublisher` variable

Thank you for the tip! 
I don't usually mess with terminal, but I've found out `export LD_LIBRARY_PATH=./libsteam_api.so:$LD_LIBRARY_PATH ; ./gmpublisher` command does everything needed.
