### ISSUE TITLE
[Linux] "Open Addon Location" doesn't work

### ISSUE THREAD

**Issue by RavMda** [WilliamVenner/gmpublisher#217]
When I try to click the button, it displays this message in the console:

```
xdg-open: unexpected option '--select'
Try 'xdg-open --help' for more information.
```

Maybe this can help:
https://github.com/tauri-apps/plugins-workspace/issues/999#issuecomment-1965624515

**Comment by RavMda** [comment]
Now it fails to compile with multiple errors...

![image](https://github.com/WilliamVenner/gmpublisher/assets/49620461/39b4fa9b-e453-477e-b3bb-fff8c6d121a6)

**Comment by WilliamVenner** [comment]
I haven’t finished the update yet because I have assignments to do. You are welcome to send in a PR
