### ISSUE TITLE
Steam error: Limit exceeded

### ISSUE THREAD

**Issue by voltageeee** [WilliamVenner/gmpublisher#219]
![image](https://github.com/WilliamVenner/gmpublisher/assets/60658899/02caeeaa-7f36-4025-b9f1-13a831a25d67)
Every time i try to upload an addon, i get this error, no matter which image i use.

**Comment by WilliamVenner** [comment]
You've been rate limited or have hit some sort of maximum. Nothing can be done from gmpublisher's point of view, sorry
