### ISSUE TITLE
 workshop  download

### ISSUE THREAD

**Issue by genrihx2** [WilliamVenner/gmpublisher#237]
![image](https://github.com/user-attachments/assets/c7e8a2c0-a98a-4d20-a906-1a20cdd44524)

error  download workshop     https://steamcommunity.com/workshop/filedetails/?id=503311892

**Comment by WilliamVenner** [comment]
what is the error?

**Comment by genrihx2** [comment]
no  download

**Comment by WilliamVenner** [comment]
Hover over the red "error" box, it should tell you which error it is

**Comment by genrihx2** [comment]
![image](https://github.com/user-attachments/assets/792ea557-b868-417d-974d-a0a7bcc74446)

I check  error   
works

**Comment by WilliamVenner** [comment]
ok ¯\_(ツ)_/¯
