### ISSUE TITLE
Whitelist Bug

### ISSUE THREAD

**Issue by ravo10** [WilliamVenner/gmpublisher#25]
Seems like files within: `gamemodes/the_gamemode_name/backgrounds/file_name.jpg` is not allowed. This is actually allowed, and is used to show custom background pictures for a gamemode that is looping.

**Comment by WilliamVenner** [comment]
Works fine for me

![image](https://user-images.githubusercontent.com/14863743/117894250-d8bbab80-b2b3-11eb-876f-d953c528bc75.png)

**Comment by ravo10** [comment]
Hmm strange. This is what I get:

![image](https://user-images.githubusercontent.com/28684292/117898943-6902ec00-b2c6-11eb-9113-5b1a7e87a265.png)

**Comment by ravo10** [comment]
Soo, if I changed the name to a string like you it works... Try doing a single number like me maybe. Is not a big deal then I guess.

**Comment by WilliamVenner** [comment]
Yeah it seems that it doesn't work if the file name is a single character. Will fix.
