### ISSUE TITLE
Please help, gmpublisher quit working on me.

### ISSUE THREAD

**Issue by AlexFanatic** [WilliamVenner/gmpublisher#253]
I have used gmpublisher for a year to extract gmod add-ons and and upload mods. Now as right at this very moment, I cannot open gmpublisher on my PC anymore. Whenever it starts, it just keeps closing out immediately and I can't troubleshoot it because it says I needed to install Microsoft Edge Webview2. When trying to do that, it gave me an error saying it was already installed but I don't see the app in settings or when I search it on Windows explorer or search. Can anyone here please help me of how I can fix this? I am very much in distress right now and any help would be appreciated. Thank you.

**Comment by WilliamVenner** [comment]
Try uninstalling and reinstalling

**Comment by AlexFanatic** [comment]
Hi extremely sorry to reply this late. But I did what you said of uninstalling and reinstalling. Unfortunately it didn't solve the issue, which means still nothing is working. Is there anything else I could try? I would hate having to buy a new pc or factory reset my entire current one just for gmpublisher to work again.

**Comment by AlexFanatic** [comment]
> Try uninstalling and reinstalling

Hi sorry to reply extremely late. But I did what you said of uninstalling and reinstalling. Unfortunately it didn't solve the issue, which means still nothing is working. Is there anything else I could try? I would hate having to buy a new pc or factory reset my entire current one just for gmpublisher to work again.

**Comment by AlexFanatic** [comment]
> Sorry, I'm not sure. Perhaps try reinstalling Microsoft Edge Webview2 as well. If you're on Windows 11, you shouldn't have that installed btw, as the operating system already comes with it. Otherwise, perhaps try installing it from here https://developer.microsoft.com/en-gb/microsoft-edge/webview2/?form=MA13LH&ch=1 before installing gmpublisher.

Well yes, I am on Windows 11. Just tried re-installing Microsoft Edge Webview2. It says it failed to install because the error message claims it's already installed on my device. And what make it more confusing is I even go to control panel and there don't see Edge Webview2 anywhere in my installed apps section. Yikes, it looks like I may have no other choice but to factory reset my PC.
