### ISSUE TITLE
Possibility for alternate colors?

### ISSUE THREAD

**Issue by One-Trick-Viper** [WilliamVenner/gmpublisher#26]
This isn't exactly a bug or so. I love using this program to publish/update my addons. 

One problem however, the red outline on things that have errored for example when the file structure of a folder is wrong or when there is a file that isn't added to ignore list, is hard to see for me because I'm colorblind (mainly red and slightly green).

I was wondering if there could be a possibility for users or maybe for you to make an alternate color scheme that swaps reds for a more noticeable color?

**Comment by WilliamVenner** [comment]
Of course, I shall add this
