### ISSUE TITLE
.bsp files don't appear when I try to upload?

### ISSUE THREAD

**Issue by LAstarsla** [WilliamVenner/gmpublisher#263]
This is my first time using gmpublisher so it might be some setting I happened to miss, but when I try to enter the file directory for my map the .bsp file doesn't appear for some reason.
![Screenshot (62)](https://github.com/user-attachments/assets/572a139a-fe15-4ebc-aad2-04ed9fa84aef)
![Screenshot (63)](https://github.com/user-attachments/assets/d298d562-7aa9-457b-9db8-5e21c6492984)

**Comment by WilliamVenner** [comment]
You need to select the addon folder, not the map file. That's why the button says "Select Folder"

https://wiki.facepunch.com/gmod/Workshop_Addon_Creation

**Comment by LAstarsla** [comment]
Oh, thanks!
