### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by Be1zebub** [WilliamVenner/gmpublisher#27]
1. wrong tooltip https://i.imgur.com/z0du49H.png it happens when you switch between addons
2. it removes addons due to a bug with the Internet connection, I already told you about this in gmod discord.
3. i cant update thumbnail only. why do I need to select addon folder if I want to update only thumbnail? Please fix it if possible. although steam workshop api probably does not have such an opportunity.

**Comment by WilliamVenner** [comment]
Thanks, 2 is fixed in 2.4.0.
