### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by Srlion** [WilliamVenner/gmpublisher#28]
There is currently no way to tell on how to use this, please add one.

Your sir,
Srlion & [TSF] Mason

**Comment by WilliamVenner** [comment]
Click stuff until you figure it out! :-)

**Comment by Srlion** [comment]
@WilliamVenner But that's not how this is supposed to work? Me and [TSF] Mason can't figure it out, not sure if it's gonna be safe to click stuff to figure it out?

**Comment by Srlion** [comment]
@WilliamVenner Also I think it would be more professional if you add a readme to help people to udnerstand what this does and doesn't.
