### ISSUE TITLE
gmpublisher setup error

### ISSUE THREAD

**Issue by Blueberryy** [WilliamVenner/gmpublisher#33]
When installing process starts it opens some cmd
![FSh9miSaa8](https://user-images.githubusercontent.com/36592509/120632461-6d17c900-c482-11eb-9320-cf968d689fd8.png)
and then this message popups
![msiexec_MXV5yCMzrp](https://user-images.githubusercontent.com/36592509/120632504-79038b00-c482-11eb-9159-7f99683495b2.png)
I'm using Windows 7 OS.

**Comment by WilliamVenner** [comment]
Download the Webview2 Runtime

https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by Blueberryy** [comment]
> Download the Webview2 Runtime
> 
> https://developer.microsoft.com/en-us/microsoft-edge/webview2/

Okay thanks! You should add back that requirement to README
