### ISSUE TITLE
gmpublisher running makes steam think gmod is still open

### ISSUE THREAD

**Issue by EntranceJew** [WilliamVenner/gmpublisher#46]
i opened gmod, then gmpublisher, but i crashed gmod testing shit, yet steam still reported gmod as still running:
![gmod still thinks it's running](https://i.imgur.com/Shap3Cq.png)

hitting the "STOP" button in steam kills the webview children but gmpublisher remains running:
![killing gmpublisher](https://i.imgur.com/7t5ko5O.gif)

other processes push it offscreen but the button reverts the moment the task is killed

a little inconvenient

**Comment by WilliamVenner** [comment]
This is how Steamworks works and cannot be fixed

**Comment by WilliamVenner** [comment]
If there's something I missed in Steamworks that allows me to launch my program with gmods app ID without registering you as playing it, then I would be delighted to implement it

**Comment by EntranceJew** [comment]
Since launching gmod directly from hl2.exe is still allowed even though gmpublisher is running it would be handy to just have a button that sets window focus to gmod if it is running and launches it if it is not. or just have it open gmod anyway all the time.

it'd be a lot easier and more useful than making a big change like caching everything and not connecting to steamworks until publishing or something.
