### ISSUE TITLE
Lib Issue on Linux

### ISSUE THREAD

**Issue by DYPIXY** [WilliamVenner/gmpublisher#54]
./gmpublisher_2.7.1_linux64: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory

**Comment by WilliamVenner** [comment]
https://github.com/WilliamVenner/gmpublisher/releases/download/2.7.1/gmpublisher_2.7.1_linux64.tar.gz

Here you go; forgot to include that dependency with the program.
