### ISSUE TITLE
Left 4 Dead 2 support

### ISSUE THREAD

**Issue by xDShot** [WilliamVenner/gmpublisher#61]
Native linux tool like this with L4D2 workshop support would be nice. Current solutions are either Authoring Tools (slow, buggy, abandoned) or Crowbar (buggy)

**Comment by WilliamVenner** [comment]
Sorry but this will not happen. gmpublisher is only for Gmod.

**Comment by xDShot** [comment]
I hope someone will do fork then eventually.
