### ISSUE TITLE
Steamworks API Error?

### ISSUE THREAD

**Issue by NoleColt** [WilliamVenner/gmpublisher#62]
Everytime I hit publish it loads everything but then gives me the Error **"A Generic Failure from the Steam Works API."**

- - Any Fix?

**Comment by CoolOppo** [comment]
Same

**Comment by Pdzly** [comment]
Same since some time ;(

**Comment by WilliamVenner** [comment]
I think `gmpublish` would have the same issue. The error comes directly from Steam.
