### ISSUE TITLE
no shared libraries

### ISSUE THREAD

**Issue by skeyvin** [WilliamVenner/gmpublisher#63]
./gmpublisher: error while loading shared libraries: libgtksourceview-3.0.so.1: cannot open shared object file: No such file or directory

specs : manjaro 64bit plasma desktop
any help?
fix :
dragndrop steam....so to /lib
execute
sudo pacman -S gtksourceview3

**Comment by WilliamVenner** [comment]
You are missing libgtksourceview

**Comment by skeyvin** [comment]
> You are missing libgtksourceview

installed gnome
restarted
doesnt work
also got gtksourceview from aur
still doenst

**Comment by WilliamVenner** [comment]
Must have installed the wrong one then

**Comment by skeyvin** [comment]
sudo pacman -S gnome
i dont think it is the wrong version
