### ISSUE TITLE
auto-downloading: false

### ISSUE THREAD

**Issue by BAILMAST** [WilliamVenner/gmpublisher#66]
Add a setting that enables/disables auto-downloading of addons/collections when you insert a link to them

**Comment by WilliamVenner** [comment]
Why do you need that?

**Comment by BAILMAST** [comment]
Because large collections are rapidly starting to load all the addons that are in it, there is no urgent need for this function, but it would still make this world better 😃

**Comment by WilliamVenner** [comment]
Well yeah, that is the point of the "Downloader", I don't see why anyone would expect it to _not_ download stuff automatically, or why that's bad

**Comment by WilliamVenner** [comment]
I will add it if you can just explain why it's needed!

**Comment by BAILMAST** [comment]
In very large collections, instead of clicking on each addon separately and copying its link, I usually inserted a link to the collection itself and downloaded the addons that I needed

**Comment by BAILMAST** [comment]
By usually I meant using Steam Workshop Downloader
