### ISSUE TITLE
Can't upload Addons to Workshop

### ISSUE THREAD

**Issue by Lame-Game** [WilliamVenner/gmpublisher#67]
Every time I want to upload an Addon it says "Steam Error: a generic failure from the steamworks API
![unknown](https://user-images.githubusercontent.com/63804278/140566408-efc70343-82d2-482f-9441-7b10abc9a53a.png)
"

**Comment by WilliamVenner** [comment]
If the same thing happens with other Workshop publishers, gmpublisher is not at fault
