### ISSUE TITLE
Downloader max ids limit? Batch downloading?

### ISSUE THREAD

**Issue by Be1zebub** [WilliamVenner/gmpublisher#73]
Hi, I want to download 176 addons from the workshop - but it looks like there is a limit in the gpublisher.
When I paste 176 ids separated by commas in entry, it just stroke the input field in red.
What is the limit and why is it limited?   

Also, it would be great to add a button to pack all downloaded addons into a zip archive.

**Comment by WilliamVenner** [comment]
Might be this code, I am unsure exactly of what its purpose was, but maybe your IDs are malformed somehow

https://github.com/WilliamVenner/gmpublisher/blob/master/app/pages/Downloader.svelte#L153-L157

**Comment by Be1zebub** [comment]
my ids are separated by commas  
im shure its not malformed
`1907060869, 2659607667, 2659610837, 106926982, 2618163541, 2676064167, 2663994021, 282498239, 925184078, 848953556, 848953609, 848953359, 873302121, 1540223847, 1655743290, 1655753632, 1918153600, 2168676821, 2274808442, 2274813023, 2637209035, 2640279709, 2637223583, 2640274798, 2642827177, 2642817723, 2633470434, 1357913645, 2495300496, 2611559098, 2162408388, 1900562881, 2605363456, 757604550, 2596798540, 2595071184, 150455514, 239531104, 157495662, 844579400, 104483020, 106929308, 2221251087, 2212091695, 2386940956, 1870505321, 582366370, 675824914, 2579891120, 536896260, 2579284565, 2577630061, 2558150898, 2559426779, 104482086, 104575630, 2106330193, 2546002427, 344795193, 2493778309, 2536492812, 2529802557, 2529785777, 2522265613, 2513275664, 1741984575, 2519892972, 2512849838, 2509672855, 1987521428, 2503194813, 2497427837, 2497150824, 2492769706, 220336312, 161451189, 531849338, 1601009560, 913248065, 104635582, 1945909088, 104648051, 2456881554, 2467846835, 104604709, 157560152, 104576786, 104604943, 1712956238, 531458473, 1691476873, 2044112738, 1994928627, 111364507, 267610127, 2171836856, 470366741, 170917418, 2381919381, 104691717, 729710362, 1439434746, 107590810, 507040054, 975506888, 105908087, 2440091840, 2396796441, 2295000846, 2395395483, 2384188626, 109643223, 1586738099, 112806637, 737076540, 572310302, 264467687, 2004023752, 771487490, 2156004721, 2384188626, 109643223, 1586738099, 112806637, 737076540, 572310302, 264467687, 2004023752, 771487490, 2156004721, 2155366756, 2256491552, 2225564383, 2244923447, 2250882958, 2233731395, 2288784152, 1823045812, 126101775, 111895870, 104601200, 282164100, 279079869, 120629004, 1542466462, 746600040, 2129722524, 936480337, 167306064, 1328566021, 871426788, 1125980817, 2143558752, 880205916, 2186553332, 108311116, 104609986, 405793043, 2114769998, 1907562709, 2158980540, 2193322364, 415143062, 2171726768, 104605841, 1542450088, 1983329448, 2137567877, 1402239310, 499280258, 2027577882, 1894793531, 2018524991, 2004611129, 104815552, 104603291`

**Comment by Be1zebub** [comment]
same with ids separated with newlines
[ids.txt](https://github.com/WilliamVenner/gmpublisher/files/7891937/ids.txt)

**Comment by Be1zebub** [comment]
yes, you are right - but why is this a problem for the gpublisher?
![image](https://user-images.githubusercontent.com/34854689/150015228-c0287255-0240-47fa-9a24-79ce09c79dc9.png)

**Comment by WilliamVenner** [comment]
I have no idea. its bad UX :V
