### ISSUE TITLE
Batch mode support?

### ISSUE THREAD

**Issue by biorisk2** [WilliamVenner/gmpublisher#77]
New to gmpublisher, might be a a way to do it and I just don't know of it but.

Writing a nodeJS app to mass extract all GMA's by opening the GMA, when the extraction is complete, the folder opens.

So anyways, around 300 folders were opened and it nearly killed my rig.

Is there a way to stop the folder from opening post-extraction?

**Comment by WilliamVenner** [comment]
You don't need to use gmpublisher for that. Use gmad in the gmod bin folder

**Comment by WilliamVenner** [comment]
Also I'm pretty sure gmpublisher does not open folders automatically, and if it does there is a way to turn it off?
