### ISSUE TITLE
Addon page does not exist

### ISSUE THREAD

**Issue by CassieCatYT** [WilliamVenner/gmpublisher#79]
Whenever it finishes uploading it opens what I assume is supposed to be the webpage, but I get redirected to the steam community error processing your request page, making me think that the addon page was not created. Can anyone help me with this?
![image](https://user-images.githubusercontent.com/94768673/163674816-723e34ec-447e-4e81-9e0e-de82dbb55f28.png)

**Comment by WilliamVenner** [comment]
You need to login to Steam

**Comment by CassieCatYT** [comment]
do you mean to upload or to view the page?

**Comment by CassieCatYT** [comment]
because I was logged in when I uploaded it

**Comment by WilliamVenner** [comment]
Look at the screenshot, you are not logged in on your browser?

**Comment by CassieCatYT** [comment]
ok, it works now

**Comment by CassieCatYT** [comment]
Now the map that I uploaded won't show up in gmod.
