### ISSUE TITLE
Addon over 4 GB seems to overwrite itself

### ISSUE THREAD

**Issue by qfoxb** [WilliamVenner/gmpublisher#89]
Having an item over 4096 MB seems to overwrite itself past that, after updating my addon to have over 4096mb of files it only shows how many mb it would have **over** 4096 mb on the steam workshop as well as in-game.

**Comment by WilliamVenner** [comment]
It seems that this is a Steam issue. Steam silently just rejects Workshop uploads larger than 4096 MiB, at least for Gmod, and serves an empty file. In my testing gmpublisher had no problem packing 8 GiB into a .gma and extracting that .gma.
