### ISSUE TITLE
My addons got deleted

### ISSUE THREAD

**Issue by CJDKing** [WilliamVenner/gmpublisher#93]
When I extracted an addon using gmpublisher, it overwrote my current addons folder and deleted everything inside it.

![image](https://user-images.githubusercontent.com/79478319/174771535-27ef85bc-6ea1-40e2-8b5c-1a0d98023b93.png)

**Comment by WilliamVenner** [comment]
This was fixed in the latest update. Your addons folder can be found in the recycle bin, btw.
